---
- name: get es plugins
  shell: /usr/share/elasticsearch/bin/plugin --list
  register: es_installed_plugins

- name: elasticsearch plugins | install user defined plugins
  shell: "/usr/share/elasticsearch/bin/plugin --verbose --install {{ item.options }}"
  when: "'- {{ item.name }}' not in es_installed_plugins.stdout"
  with_items: es_plugins
  notify: restart elasticsearch

# do soemthing else here...
- name: elasticsearch plugins | get postgresql jdbc jar
  get_url:
    url: http://jdbc.postgresql.org/download/postgresql-9.3-1102.jdbc41.jar
    dest: /usr/share/elasticsearch/plugins/jdbc/postgresql-9.3-1102.jdbc41.jar
    mode: 0644
